### ISSUE TITLE
Forbid regexes instead of substrings

### ISSUE THREAD

**Issue by wh1t3cAt1k** [mrseanryan/tslint-ban-snippets#9]
I found my snippets list to be a bit verbose, whilst a regex would have been much terser.
Is it possible to submit this as a feature request?

**Comment by wh1t3cAt1k** [comment]
(this can be implemented as a separate rule to avoid conflicts)

**Comment by mrseanryan** [comment]
@wh1t3cAt1k  nice suggestion!

I'm adding a 2nd way to configure the same rule.

So in the `banned` section, you can use `regexSnippets` instead of `snippets`

```
                "banned": [
                    {
                        "regexSnippets": ["return void [reject|resolve]"],
                        "message": "Please do not return void - instead place the return statement on the following line.",
                        "includePaths": [".ts", ".tsx"],
                        "excludePaths": []
                    }
                ]

```

Perhaps you can have look, and if this is useful, I will merge and release ...

**Comment by mrseanryan** [comment]
Here is the pull request, if you wish to see

https://github.com/mrseanryan/tslint-ban-snippets/pull/10

**Comment by mrseanryan** [comment]
@wh1t3cAt1k  closing

let me know if I can help again!
